image: node:latest

stages:
  - install
  - build
  - copy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm build

production:
  stage: copy
  script:
    - ls -la
