image: node:latest

      

stages:
  - install
  - build
  - copy

cache:
  paths:
    - node_modules/
  untracked: true

install:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
  stage: install
  script:
    - PATH="$PATH:/shared/node/bin/"
    - npm install

build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
  stage: build
  script:
    - PATH="$PATH:/shared/node/bin/"
    - /shared/node/bin/npm run build
    - tar -zcvf build.tgz dist 
    - /jfrogcli/jfrog config add $FATALFRONT_REPO_KEY --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS --interactive=false
    - rt u --build-name="Test Project" --build-number="${CI_BUILD_TAG}" build.tgz $FATALFRONT_REPO_KEY

production:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
  stage: copy
  script:
    - PATH="$PATH:/shared/node/bin/"
    - cp -r dist/*/* /var/www/html