image: node:latest

stages:
  - install
  - build
  - copy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - PATH="$PATH:/shared/node/bin/"
    - npm install

build:
  stage: build
  script:
    - PATH="$PATH:/shared/node/bin/"
    - /shared/node/bin/npm run build

production:
  stage: copy
  script:
    - PATH="$PATH:/shared/node/bin/"
    - ls -la