image: node:latest

stages:
  - install
  - build
  - copy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm run build

variables:
  PROJECT_PATH: "$CI_PROJECT_DIR"
  APP_OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts/app"

build_app:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn ng build --prod
    - ls -la
  after_script:
    - cp $PROJECT_PATH/Dockerfile $APP_OUTPUT_PATH
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - $APP_OUTPUT_PATH
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull


production:
  stage: copy
  script:
    - ls -la